### ISSUE TITLE
Feedback from Milestone 2

### ISSUE THREAD

**Issue by omar-narine20** [kostas24/VCRTSNEW#13]
- Missing clear button
- Fields should be cleared following submission
- Need to update timestamp to include date
- Needs acknowledgement following account creation
- Move to the field labels next to the field instead of being inside of the field by default
- Make this look fire 
- Change font, current font (Comic Sans, I think) give the GUI the illusion of being outdated. Look for more modern or simple style font 
- Non necessary feature: Prevent submission without all fields being submitted

**Comment by Rudy182** [comment]
Possibly change titles depending on what frame is up
save users in 2 files? maybe

**Comment by omar-narine20** [comment]
> Possibly change titles depending on what frame is up save users in 2 files? maybe

I think that the title already change, I'll have to check on that because I remember working on.
